server:
  port: 8095
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 172.16.116.100
  rabbitmq:
    host: 172.16.116.100
    virtual-host: /fengge
    username: fengge
    password: fengge
auth:
  jwt:
    publicKeyPath: D:\\project-0826\\secret\\rsa.pub
    cookieName: GMALL_TOKEN
