server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 172.16.116.100
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.116.100:3306/guli_pms
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:mapper/pms/**/*.xml
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.atguigu.gmall: debug
